### ISSUE TITLE
How to set offset?

### ISSUE THREAD

**Issue by NotNite** [coral/ddp-rs#3]
Heya - building a project with WLED and I decided to use this library, but I can't figure out how to set the offset of the data I'm sending. Calling `write(&[255, 255, 255])` lights up only the first pixel on my LED strip and I'm not sure how to move it (and sending the entire block starting from zero is wasteful).

**Comment by coral** [comment]
@NotNite Hey NotNite, tbh I never really considered the usecase of sending something with a fixed offset since the data is so small that i just send it all every frame (you can push 87,950 pixels @ 45 FPS over a 100M link with DDP) so bandwidth wasn't really... something I did care about.

HOWEVER, for the purity of it i'll add a function that allows you to send with an offset.

**Comment by NotNite** [comment]
Thank you!

**Comment by NotNite** [comment]
I ended up attempting to build the project by spamming packets and ran into issues. My strip is 600 LEDs long (two strips together), but the max data length is 480. Sending `480 * 3` bytes works, but doesn't fill the entire bar (cropped the right side in this screenshot):

![image](https://github.com/coral/ddp-rs/assets/44414597/2e868278-393e-4ccb-90b0-a440afd2194f)

But trying to send the full 600 at once results in corruption:

![image](https://github.com/coral/ddp-rs/assets/44414597/c58f5d77-8910-49e5-b807-ff8fab04c376)

It seems that anything not guaranteed to fit into one packet will corrupt.

**Comment by coral** [comment]
Yeah tbh I realized I implemented the offset wrong and I don't slice it correctly so this is on me to fix. Will get to it

**Comment by coral** [comment]
@NotNite just published a new version, there's now a `write_offset(data, offset)` function and I fixed the garbage data bug you discovered. Lmk if that works for you.

**Comment by NotNite** [comment]
Seems to work, thanks!
